### ISSUE TITLE
PDF - Icons not visible when page is shrinked

### ISSUE THREAD

**Issue by vinoddevela-gep** [GEP-GitHub/Base-Document#15]
Hi,

When I shrinked the page to include the console to be docked to the right, I observed that the icons are hidden. Not sure whether this will be accepted as an issue or a design intent.

![image](https://user-images.githubusercontent.com/40360918/52779354-fadf0880-306d-11e9-88ed-788128e49e37.png)

CC: @ashokkumarkaruturi-gep  @vidhyasagarbhogavalli-gep @paritoshfulara-gep  @Moizuddinkhaja-gep  @gepwyousef

**Comment by Moizuddinkhaja-gep** [comment]
@vinoddevela-gep 
This issue is resolved.  Please use smart-pdfviwer : 1.0.7 .
![image](https://user-images.githubusercontent.com/40623504/52849236-9176fc80-3136-11e9-922b-c805ec85b452.png)

Cc : @gepwyousef  @sachinmule-gep  @rahulpatel-gep

**Comment by vinoddevela-gep** [comment]
@Moizuddinkhaja-gep:  

Issue verified and changes are working as expected.

CC: @ashokkumarkaruturi-gep @vidhyasagarbhogavalli-gep @paritoshfulara-gep @Moizuddinkhaja-gep @gepwyousef
